version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Flask-API
    ports:
      - "0.0.0.0:5000:5000"  # Bind to all interfaces (accessible externally)  
    volumes:
      - Course_Proposal:/data/db
    environment:
      - FLASK_ENV=development
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  Course_Proposal:
    driver: local