version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-api
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    volumes:
      - shoppingList:/data/db  
    environment:
      - FLASK_ENV=development  
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  shoppingList:  # Declare the named volume
    driver: local